import UIKit

// Generated by scripts/generate_uicolor_assets.sh. Do not edit manually.
extension UIColor {
    static var accentColor: UIColor { ToDoListAsset.Assets.accentColor.color }
    static var border: UIColor { ToDoListAsset.Assets.border.color }
    static var appGray: UIColor { ToDoListAsset.Assets.gray.color }
    static var primaryText: UIColor { ToDoListAsset.Assets.primaryText.color }
    static var secondaryText: UIColor { ToDoListAsset.Assets.secondaryText.color }
    static var appSeparator: UIColor { ToDoListAsset.Assets.separator.color }
    static var appYellow: UIColor { ToDoListAsset.Assets.yellow.color }
}
