#!/bin/bash
set -euo pipefail

SRCROOT="${SRCROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
ASSETS_FILE_CANDIDATES=(
  "$SRCROOT/Derived/Sources/TuistAssets+ToDoList.swift"
  "$SRCROOT/ToDoList/Derived/Sources/TuistAssets+ToDoList.swift"
  "${DERIVED_SOURCES_DIR:-}/TuistAssets+ToDoList.swift"
)
OUTPUT_FILE="$SRCROOT/Generated/Sources/UIColor+AppColors.generated.swift"

ASSETS_FILE=""
for candidate in "${ASSETS_FILE_CANDIDATES[@]}"; do
  if [[ -n "${candidate:-}" && -f "$candidate" ]]; then
    ASSETS_FILE="$candidate"
    break
  fi
done

if [[ -z "$ASSETS_FILE" ]]; then
  echo "warning: Tuist assets file not found. Expected TuistAssets+ToDoList.swift"
  exit 0
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"

BLOCKED_NAMES=(
  black darkGray lightGray white gray red green blue cyan yellow magenta orange purple brown clear
  separator opaqueSeparator placeholderText systemBackground secondarySystemBackground tertiarySystemBackground
  systemGroupedBackground secondarySystemGroupedBackground tertiarySystemGroupedBackground
  label secondaryLabel tertiaryLabel quaternaryLabel link
)

is_blocked_name() {
  local name="$1"
  for blocked in "${BLOCKED_NAMES[@]}"; do
    if [[ "$blocked" == "$name" ]]; then
      return 0
    fi
  done
  return 1
}

to_app_prefixed_name() {
  local name="$1"
  local first rest
  first="$(printf "%s" "$name" | cut -c1 | tr '[:lower:]' '[:upper:]')"
  rest="$(printf "%s" "$name" | cut -c2-)"
  printf "app%s%s" "$first" "$rest"
}

asset_names=()
while IFS= read -r line; do
  asset_names+=("$line")
done < <(
  sed -n '/public enum Assets {/,/^[[:space:]]*}/p' "$ASSETS_FILE" \
  | sed -nE 's/^[[:space:]]*public static let ([A-Za-z_][A-Za-z0-9_]*) = ToDoListColors\(name: ".*"\)/\1/p'
)

if [[ ${#asset_names[@]} -eq 0 ]]; then
  echo "warning: No color assets found in $ASSETS_FILE"
  exit 0
fi

{
  echo "import UIKit"
  echo
  echo "// Generated by scripts/generate_uicolor_assets.sh. Do not edit manually."
  echo "extension UIColor {"
  for asset_name in "${asset_names[@]}"; do
    property_name="$asset_name"
    if is_blocked_name "$property_name"; then
      property_name="$(to_app_prefixed_name "$property_name")"
    fi
    echo "    static var $property_name: UIColor { ToDoListAsset.Assets.$asset_name.color }"
  done
  echo "}"
} > "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE from $ASSETS_FILE"
